# Generated by Django 5.1.1 on 2024-11-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_scheduleritem_scheduleitem_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.schedule'),
            preserve_default=False,
        ),
    ]
