# Generated by Django 5.1.1 on 2024-11-03 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_scheduleitem_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='next_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
